<?php
//Subscribe Youtube Channel Peternak Kode on https://youtube.com/c/peternakkode
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sia_transaksi_waringin_h_model extends CI_Model
{

    public $table = 'sia_transaksi_waringin_h';
    public $id = 'id_transaksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->where('isactive', 1);
        $this->db->group_start();
        $this->db->like('id_transaksi', $q);
	$this->db->or_like('tgl_input', $q);
	$this->db->or_like('no_ref', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('created_by', $q);
	$this->db->or_like('update_by', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('update_at', $q);
	$this->db->or_like('isactive', $q);
	$this->db->group_end();
            $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by("aa." . $this->id, $this->order);
       // $this->db->where('isactive', 1);
        $this->db->group_start();
	$this->db->or_like('aa.tgl_input', $q);
	$this->db->or_like('aa.no_ref', $q);
	$this->db->or_like('aa.ket', $q);
	$this->db->group_end();
            $this->db->limit($limit, $start);
        // $this->db->join('sia_transaksi_waringin bb', 'bb.id_transaksi_h=aa.id_transaksi', 'left');
        return $this->db->get($this->table . " aa")->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // move to bin
    function bin($id){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, array('isactive'=>0));
    }

}

/* End of file Sia_transaksi_waringin_h_model.php */
/* Location: ./application/models/Sia_transaksi_waringin_h_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-03-23 03:34:58 */
/* http://harviacode.com */
/* Customized by Youtube Channel: Peternak Kode (A Channel gives many free codes)*/
/* Visit here: https://youtube.com/c/peternakkode */